#依赖的基础镜像jdk8
FROM java:8
#需要暴露出去的端口，也就是我项目的端口
EXPOSE 8080
#作者信息
MAINTAINER TeamHammer
#Tomcat 默认使用/tmp作为工作目录。这个命令的效果是：在宿主机的/var/lib/docker目录下创建一个临时文件并把它链接到容器中的/tmp目录
VOLUME /tmp
#将主机环境的jar包，以文件名demo.jar添加到docker镜像中
ADD /target/timeMaster-0.0.1-SNAPSHOT.jar timeMaster.jar
#启动容器之后，默认的运行命令
ENTRYPOINT ["java","-jar","/timeMaster.jar"]
